name: Cowsay file
on: push
jobs:
    build-job:
        name: Write & Read a Cowsay file
        runs-on: ubuntu-22.04
        steps:
            - name: echo
              run: echo "This is build step"

            - name: checkout repo
              uses: actions/checkout@v4

            - name: List file
              run: ls -ltra

            - name: Execute shell script
              run: |
               chmod +x execute_cowsay.sh
               ./execute_cowsay.sh
            
            - name: Upload files
              uses: actions/upload-artifact@v4
              with:
                name: Dragon-file
                path: Dragon.txt
            
    test-job:
        name: Checking file existance
        runs-on: ubuntu-22.04
        needs: 
            - build-job
        steps:
            - name: Download files
              uses: actions/download-artifact@v4
              with:
                name: Dragon-file

            - name: echo
              run: echo "This is testing step"
            
            - name: check file
              run: grep -i "Dragon" Dragon.txt
    
    deploy-job:
        name: Deploying step
        runs-on: ubuntu-22.04
        needs: 
            - build-job
            - test-job
        steps:
            - name: Download files
              uses: actions/download-artifact@v4
              with:
                name: Dragon-file

            - name: echo
              run: echo "Deploying..." 
            
            - name: Deploy file
              run: cat Dragon.txt
            
            

    