name: Cowsay file
on: 
  # # schedule:
  #   # - cron: "*/1 * * * *"
  # workflow_dispatch: 
  push
env:
    WORKFLOW_VAR: WORKFLOW_VARIABLE
jobs:
    build-job:
        name: Write & Read a Cowsay file
        timeout-minutes: 0.10
        env:
            JOB_VAR: JOB_VARIABLE
        runs-on: ubuntu-22.04
        steps:
            - name: echo
              env:
                STEP_VAR: STEP_VARIABLE
              run: echo $STEP_VAR

            - name: echo workflow variable
              run: |
                echo $WORKFLOW_VAR
                echo $JOB_VAR
                echo ${{ secrets.PASSWORD }}
                echo ${{ vars.USERNAME }}

            - name: checkout repo
              uses: actions/checkout@v4

            - name: List file
              run: ls -ltra

            - name: Execute shell script
              run: |
               chmod +x execute_cowsay.sh
               ./execute_cowsay.sh
            
            - name: Upload files
              uses: actions/upload-artifact@v4
              with:
                name: Dragon-file
                path: Dragon.txt
            
    # test-job:
    #     name: Checking file existance
    #     runs-on: ubuntu-22.04
    #     needs: 
    #         - build-job
    #     steps:
    #         - name: Download files
    #           uses: actions/download-artifact@v4
    #           with:
    #             name: Dragon-file

    #         - name: echo
    #           run: echo "This is testing step"
            
    #         - name: check file
    #           run: grep -i "Jayesh" Dragon.txt
    
    deploy-job:
        name: Deploying step
        runs-on: ubuntu-22.04
        needs: 
            - build-job
            # - test-job
        concurrency: 
          group: 
            production-deploy
          cancel-in-progress: true
        steps:
            - name: Download files
              uses: actions/download-artifact@v4
              with:
                name: Dragon-file

            - name: echo
              run: echo "Deploying..." 
            
            - name: Deploy file
              run: cat Dragon.txt
            
            - name: sleep
              run: sleep 600s
            
            

    