name: First Example
on:
  push:
    branches: 
      - main
      - '!feature/*'
    paths-ignore: 
      - README.me
  pull_request: 
    branches: 
      - main
    paths: 
      - README.me
    types: 
      - opened
      - closed
  workflow_dispatch:
jobs:
    first-job:
        if: github.ref == 'refs/heads/main'
        name: pull repo
        runs-on: ubuntu-22.04
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
              
            - name: Execute echo
              run: echo "hi"
            
            - name: List files
              run: ls
            
            - name: print readme
              run: cat README.md