name: Matrix Example
on:
    push:
    workflow_dispatch:
jobs:
    docker-run-on:
        strategy:
          matrix:
            os:
                - ubuntu-latest
                - ubuntu-20.04
                - windows-latest
            images:
                - hello-world
                - alpine
        name: Running ${{matrix.images}} on ${{matrix.os}}
        runs-on: ${{ matrix.os }}
        steps:
            - name: Echo details
              run: docker info
            
            - name: Run docker ${{matrix.images}}
              run: docker run ${{matrix.images}}
